# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb6a28d1d1cd2deca10198a8af044b589da32a7d483db18620cc85ea713ecd5df7c5e16a3a1650f4c4e9b7b546f09270f85155f43d909b0c1c9a03befca24b83

test:
  secret_key_base: d7fb73e1ba04401279f30c46a4091f4f57744da099ba34e8787ef9a9f33ef94d2dde934aaf3ca2a41a9aa3d7e7e75e1a8937deb1493608529ed8acc5cde3ccc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
